import 'package:pdf/pdf.dart';
import 'dart:typed_data';
import 'package:pdf/widgets.dart' as pw;
import 'package:reportautomation/features/report_generator/models/report_json_model.dart';

// Conditional imports
import 'pdf/pdf_storage_stub.dart'
    if (dart.library.io) 'pdf/pdf_storage_io.dart'
    if (dart.library.html) 'pdf/pdf_storage_web.dart';

class PdfService {
  String _formatReadableDate(dynamic date) {
    try {
      final DateTime parsed = date is DateTime
          ? date
          : DateTime.parse(date.toString());

      return '${_monthName(parsed.month)} ${parsed.day}, ${parsed.year}';
    } catch (_) {
      return date.toString(); // fallback if parsing fails
    }
  }

  String _monthName(int month) {
    const months = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];
    return months[month - 1];
  }

  Future<({String path, Uint8List bytes})> generateReportPdf(
    ReportJsonModel report,
  ) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (_) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              report.title,
              style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.Text('Generated by: ${report.generatedBy}'),
          pw.Text('Date: ${_formatReadableDate(report.date)}'),
          pw.SizedBox(height: 20),
          ...report.sections.map((section) {
            String content = section.content ?? '';
            // Basic fix for latin1 encoding issues if any (not usually needed with utf8)
            // content = utf8.decode(content.runes.toList());

            if (section.type == 'paragraph') {
              return pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 8),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    if (section.title != null)
                      pw.Text(
                        section.title!,
                        style: pw.TextStyle(
                          fontSize: 16,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                    pw.Text(content),
                  ],
                ),
              );
            }

            if (section.type == 'table') {
              return pw.TableHelper.fromTextArray(
                headers: section.headers ?? [],
                data: section.rows ?? [],
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              );
            }

            return pw.SizedBox();
          }),
          if (report.recommendations.isNotEmpty) ...[
            pw.SizedBox(height: 20),
            pw.Text(
              'Recommendations',
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
            ),
            ...report.recommendations.map((rec) => pw.Bullet(text: rec)),
          ],
        ],
      ),
    );

    final bytes = await pdf.save();
    final fileName = 'report_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final path = await savePdfBytes(bytes, fileName);
    return (path: path, bytes: bytes);
  }

  Future<({String path, Uint8List bytes})> generateReportPdfWithSignature(
    ReportJsonModel report,
    String signaturePath,
  ) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (_) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              report.title,
              style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.Text('Generated by: ${report.generatedBy}'),
          pw.Text('Date: ${_formatReadableDate(report.date)}'),

          pw.SizedBox(height: 20),
          ...report.sections.map((section) {
            String content = section.content ?? '';
            // content = utf8.decode(content.runes.toList());

            if (section.type == 'paragraph') {
              return pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 8),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    if (section.title != null)
                      pw.Text(
                        section.title!,
                        style: pw.TextStyle(
                          fontSize: 16,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                    pw.Text(content),
                  ],
                ),
              );
            }

            if (section.type == 'table') {
              return pw.TableHelper.fromTextArray(
                headers: section.headers ?? [],
                data: section.rows ?? [],
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              );
            }

            return pw.SizedBox();
          }),
          if (report.recommendations.isNotEmpty) ...[
            pw.SizedBox(height: 20),
            pw.Text(
              'Recommendations',
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
            ),
            ...report.recommendations.map((rec) => pw.Bullet(text: rec)),
          ],
          pw.SizedBox(height: 20),
          pw.Divider(thickness: 2),
          pw.SizedBox(height: 10),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Legally Signed by User',
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 16,
                      color: PdfColors.blue,
                    ),
                  ),
                  pw.Text(
                    'Date: ${DateTime.now().toIso8601String().split('T')[0]}',
                    style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
                  ),
                ],
              ),
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.green, width: 2),
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                child: pw.Text(
                  'VERIFIED SIGNATURE',
                  style: pw.TextStyle(
                    color: PdfColors.green,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );

    final bytes = await pdf.save();
    final fileName =
        'report_signed_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final path = await savePdfBytes(bytes, fileName);
    return (path: path, bytes: bytes);
  }
}
