// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTp8BL4k0P1cwu9CvS8aMWOmJvvkcjEDk',
    appId: '1:617343842163:web:7a54fc540bed2e5484f706',
    messagingSenderId: '617343842163',
    projectId: 'reportingautomation-47bd8',
    authDomain: 'reportingautomation-47bd8.firebaseapp.com',
    storageBucket: 'reportingautomation-47bd8.firebasestorage.app',
    measurementId: 'G-QK2BG3Q9Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkuYxjtqYJ-_FBmxDg7tXmBZnBBLntsPA',
    appId: '1:617343842163:android:43f66fa5842ba7a084f706',
    messagingSenderId: '617343842163',
    projectId: 'reportingautomation-47bd8',
    storageBucket: 'reportingautomation-47bd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUxPggJeyGvXgQjQWn9v67fV_jJm2atN0',
    appId: '1:617343842163:ios:83dee3770bc6180284f706',
    messagingSenderId: '617343842163',
    projectId: 'reportingautomation-47bd8',
    storageBucket: 'reportingautomation-47bd8.firebasestorage.app',
    iosBundleId: 'com.leos.ReportAutomation.reportautomation',
  );
}
