import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:reportautomation/app.dart';
import 'package:reportautomation/features/report_generator/providers/report_provider.dart';
import 'firebase_options.dart'; // We will need to generate this or mock it for now.
import 'package:flutter_dotenv/flutter_dotenv.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env");
  // Initialize Firebase - Assuming firebase_options.dart will be generated by flutterfire configure
  // For now, we'll try to initialize default app or handle error gracefully if config missing
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint(
      "Firebase initialization failed (expected if not configured): $e",
    );
    // In a real app we might want to halt or show error, but for dev structure we proceed
  }

  runApp(
    MultiProvider(
      providers: [ChangeNotifierProvider(create: (_) => ReportProvider())],
      child: const ReportAutomationApp(),
    ),
  );
}
